version: 0.0
os: linux
files:
  - source: /
    destination: /opt/webapi  # replace with your app's directory
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu  # replace with your user
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu  # replace with your user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu  # replace with your user
