version: '3.7'

services:

  webapi-core:
    build:
      context: ./
    container_name: webapi_core
    depends_on:
      - postgres_db
      - mongo_db
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8080:8080
      - 5678:5678
    volumes:
      - ./:/app
    command:
      - uvicorn
      - webapi.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
      - --reload # take away in prod
    restart: unless-stopped

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres # local development only, will make something complicated for prod
      - POSTGRES_USER=YRTEDXCUYVUFUCKYOURMOTHERHBIJKMvdfsgji
      - POSTGRES_PASSWORD=&R£$RDJ_!fgsddsftgrTVYSAIUOANSopm7894235erf.mksvdfcwetgzvfeedarvzSVFsr8yikvcmxfdc
    ports:
      - "5432:5432"

  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: hjdbfgkydrtmksaewtrYTUASVBHZXJNKASR43edcs
      MONGO_INITDB_ROOT_PASSWORD: D&RE*&WYH*UJDdfasgrtsfbvd654waefcvdxrcsZd65
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  postgres_data:
  mongodb_data: